### ISSUE TITLE
Implementing scan bar code with product key and weight

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#100]
The pos now allows read code bar printed with product key  and quantity (weight) separate for tab character , so the POS read first product key and transfer focus to quantity field and capture using the scanner and set the focus to scanner a new product

**Comment by marcalwestf** [comment]
tested manually, simulating the scan bar
1.- select product field
2.- type in the product code (or name or UPC/EAN)
3.- type in TAB key.
A new line is created with quantity=0 or the existing line with the product is selected.
Focus is set on field quantity.
4.- type in the quantity.
5.- type in ENTER
The quantity entered is added to the existing quantity.
The focus goes back to the product field
