### ISSUE TITLE
Implement other approach for fill the lookup product

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#110]
before the lookup product was filled using warehouse price view ,it not is right,  given that the price logic is more complex , the system should show the product with prices that have date valid and considering the price value breakbefore the lookup product was filled using warehouse price view ,it not is right,  given that the price logic is more complex , the system should show the product with prices that have date valid and considering the price value break

**Comment by marcalwestf** [comment]
lookup product working correctly.
Closing issue.
