### ISSUE TITLE
Adjust the font size and size resolution 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#115]
Currently the POS for 1024 x 768 size screen not show rightly

**Comment by marcalwestf** [comment]
In Swing, the POS looks crowded, but it is acceptable.
In ZK, it is not possible to distinguish the orderline items.
Still open for ZK.

See images.
![20160518_pos-1024x768-swing](https://cloud.githubusercontent.com/assets/1789408/15361814/510f9c4c-1cd0-11e6-838f-cf04c69acd9b.png)
![20160518_pos-1024x768-zk](https://cloud.githubusercontent.com/assets/1789408/15361815/5115946c-1cd0-11e6-963a-ed77ff9f0412.png)

**Comment by marcalwestf** [comment]
Now it is OK, see image
![20160519_pos-resolution](https://cloud.githubusercontent.com/assets/1789408/15411181/59f19dc2-1ddb-11e6-8d7b-0ccd56607d1f.png)

**Comment by marcalwestf** [comment]
closing issue
