### ISSUE TITLE
Add the TaxID and Name2 the partner info dialog is very necessary in special TaxId

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#120]

**Comment by marcalwestf** [comment]
In ZK : OK
In Swing: Parameters of form are disarrayed.
See image.
![20160518_pos-bp_form](https://cloud.githubusercontent.com/assets/1789408/15362501/916c66d8-1cd2-11e6-9908-3d6fe54adb20.png)

**Comment by marcalwestf** [comment]
Corrected with a0e32c863ed7da7348dd0bd8b679151cf26ef914 .
Closing issue.
