### ISSUE TITLE
In ZK, it is not possible to select a product from the smart product search combo box

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempierePOS#137]
1.- log in in ZK, open the ZK POS, create a new order
2.- click in the  smart product search area
3.- type in the smart product search area the first 3 characters of the product name or of the product key.
4.- move among the displayed products in the combo box the cursor over to the one you wish to be added to the order and click left it.
 -> Result: A different product is added. This is an error.

BTW, when the whole product name or the whole product key is entered, the correct product is added.

**Comment by marcalwestf** [comment]
I tested the changes. 
If we have for example a product whose key = OV047 (name=Cefalexina) and we type in just ov04 , we can select from the combo box with the cursor the line with the product OV047 Cefalexina and the product is added. This is OK, as can be seen in the images.
![20160718_pos_03a](https://cloud.githubusercontent.com/assets/1789408/16930103/0eda2c2c-4cf8-11e6-8be4-734ad77dc320.jpg)
![20160718_pos_04a](https://cloud.githubusercontent.com/assets/1789408/16930104/0edcdeb8-4cf8-11e6-81a8-9e2597cc073f.jpg)

**Comment by marcalwestf** [comment]
But if on the other hand we only type in ov0, which leaves a combo box with much more selections and select then the  the product OV047 Cefalexina another product is added, as can be seen in the images. This is an error.
![20160718_pos_01a](https://cloud.githubusercontent.com/assets/1789408/16930262/9a8e2f70-4cf8-11e6-9ca8-f0b6d2896ea1.jpg)
![20160718_pos_02a](https://cloud.githubusercontent.com/assets/1789408/16930366/1b688d98-4cf9-11e6-86e6-065c43542cd3.jpg)

**Comment by Raul-mz** [comment]
Hi Mario, the error was that the list sorts products by name and the IDs were not being ordered.

**Comment by marcalwestf** [comment]
last changes tested and now it works. 
Closing this issue.
