### ISSUE TITLE
The Dialog POS list  all the POS for login organization 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#31]

**Comment by e-Evolution** [comment]
Is pending of implementation for ZK

**Comment by marcalwestf** [comment]
Swing: OK
ZK: Dialog implemented, but POS Layouts are not displayed.
See image.
![20160518_pos-organizations](https://cloud.githubusercontent.com/assets/1789408/15369519/2a008f92-1cf0-11e6-8375-efdee7ddaa7f.png)

**Comment by marcalwestf** [comment]
With 438688f47acebfdae654f622af55111c8d0a578e the dialog is bigger , but no selection possible.

**Comment by yamelsenih** [comment]
Hi @marcalwestf i test it and worked..
![issue173](https://cloud.githubusercontent.com/assets/2333092/15412964/dd5b8c62-1df5-11e6-904f-ed06e3923d2f.png)

![issue172](https://cloud.githubusercontent.com/assets/2333092/15412947/bf3ecfbe-1df5-11e6-8149-dca83367b8d4.png)

**Comment by marcalwestf** [comment]
Hi @yamelsenih this is what I get...
![20160518_pos-organizations2](https://cloud.githubusercontent.com/assets/1789408/15414043/ec4c7242-1df3-11e6-80fb-54659df21144.png)

**Comment by Raul-mz** [comment]
Hi @marcalwestf  can you tell me that moment happens that case?

**Comment by marcalwestf** [comment]
With commit 5bf77ff11b7d22b0980b142d722d97134555f31a , the POS Layouts defined for the log in organization are displayed.
Closing the issue.
