### ISSUE TITLE
Rename panel and Change of Quantity Panel after of product fiel is more useful in scanner bar process

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#32]

**Comment by e-Evolution** [comment]
<img width="1919" alt="captura de pantalla 2015-12-11 a las 11 57 39 a m" src="https://cloud.githubusercontent.com/assets/786968/11751348/9bdae424-9ffe-11e5-98a2-ad989b312a7f.png">

Pending implementation for ZK

**Comment by marcalwestf** [comment]
closing issue
