### ISSUE TITLE
Resize the split bar to 50% left and 50% right 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#34]

**Comment by e-Evolution** [comment]
Reviewing ZK implementation

**Comment by e-Evolution** [comment]
<img width="1916" alt="captura de pantalla 2015-12-11 a las 1 50 26 p m" src="https://cloud.githubusercontent.com/assets/786968/11754011/40bad562-a00e-11e5-83c1-2ef6a84810a4.png">

**Comment by marcalwestf** [comment]
tested in ZK and Swing.
Closing issue.
