### ISSUE TITLE
Need to catch errors in the main class and deal with them gracefully.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempierePOS#5]
Trying the POS for the first time without setup causes an exception org.adempiere.pos.AdempierePOSException: No POS Terminal defined for User and the application hangs.

The main class needs to catch this exception and exit gracefully.

**Comment by mckayERP** [comment]
That is logging in as GardenAdmin.

**Comment by marcalwestf** [comment]
It was implemented as to catch all exceptions and offer a -more or less meaningful- message to the user.
It was tested with different scenarios like period closed.
Closing issue.
