### ISSUE TITLE
Titles of Dialogs incorrect 

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempierePOS#55]
The Product, Business Partner, Document Type and History Dialog do not have the correct Title nor the correct name of the Parameter panel. They show right now no title or just "Query Enter". Same happens to Parameter Panel.
Refer to image attached.

![20160112_pos_04](https://cloud.githubusercontent.com/assets/1789408/12272830/f2742452-b927-11e5-96b1-a7ad928933b0.png)

**Comment by Raul-mz** [comment]
The title was changed from the window according to the column name

**Comment by marcalwestf** [comment]
Bug fixed in ZK, Only Swing is missing now

**Comment by marcalwestf** [comment]
Fixed.
Closing issue.
