### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Andresdguez** [adempiere/adempierePOS#62]
Warehouse Management/Outbound Operations/Releasing Picking Shipping Order.

Release Process Order shipment

To perform the process in smart browser and have sent the search process, after the selection of destination location does not allow you to search.

Warehouse Management/Outbound Operations/Releasing Picking Shipping Order

**Comment by marcalwestf** [comment]
hi Andrés,
can it be that you intended to create the issue in the "adempiere" project?
If this is the case, you could close this issue and copy it to the "adempiere" project.
