### ISSUE TITLE
The warehouse should allow entry payment and not so for standard order

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#85]

**Comment by marcalwestf** [comment]
implemented in Swing, still to develop in ZK

**Comment by marcalwestf** [comment]
also implemented in ZK.
Closing issue.

**Comment by e-Evolution** [comment]
The payment not should depend of allocations , because you can receipt payment without invoice

**Comment by marcalwestf** [comment]
it is implemented (https://github.com/adempiere/adempierePOS/commit/3a164b0f1aab61ba8b0d26b52a136b4ca6d3c528 and https://github.com/adempiere/adempierePOS/commit/452aa9b9fc3c9d359c5618f9712133164d1eb305 )in such a way that all posible payments are considered.
Closing the issue.
