### ISSUE TITLE
Add mnemonics in the keyboard layout

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#9]

**Comment by marcalwestf** [comment]
Implemented.
It was taken into account to be compatible with existing Adempiere shortcuts.

These are the shortcuts (Explanations are in Spanish. Be so kind to translate).
F2: Nueva Orden
F3: borrar orden (si se encuentra en borrador) o cancelar orden (si se encuentra en otro estado)
F4: Diálogo de pago
F9: Diálogo de historia de órdenes
F10: Diálogo de Tipo de documento
ALT+left: navegar a Orden previa
ALT+right: navegar a Orden siguiente
Diálogo para cambiar Socio de Negocio
CTL+ALT+I: Swing
Combinación histórica: siempre ha sido así en Swing
ALT+B: ZK
En ZK no es posible utilizar combinaciones de por ejemplo CTL+ALT. 
Por eso diverge de la combinación en Swing.
ALT+L: cerrar ventana POS
ALT+I: Diálogo para seleccionar producto (falta en Swing)
ALT+P: Activar ícono de Proceso (falta en ZK)
ALT+up: navegar a línea de Orden próxima superior 
ALT+down: navegar a línea de Orden próxima inferior 
CTL+F3: borrar línea de Orden 
CTL+1: incrementar en 1 unidad cantidad línea de Orden
CTL+0: decrementar en 1 unidad cantidad línea de Orden
