### ISSUE TITLE
Remove Dialog window for payment, the idea remove any user distraction into of POS 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#90]
Currently in POS when we make a payment a dialog window is show , but it would be an user distraction.
So with goal the improve of usability we change the dialog window to payment to interior panel that is show or hide when is necessary.

**Comment by marcalwestf** [comment]
now the other icons must be disabled when the payment panel is active.

**Comment by marcalwestf** [comment]
tested in Swing and works OK.
Now the completion of an OnCredit Order has to be implemented as process due to the fact that is has been removed from the payment panel, where it actually doesn't belong to.

**Comment by e-Evolution** [comment]
Hi Mario the process was implement the option show complete prepare order, , would you testing?

**Comment by marcalwestf** [comment]
ok

**Comment by marcalwestf** [comment]
Just tested completing a Standard or a Credit Order with menu commands both in Swing and ZK.

**Comment by marcalwestf** [comment]
Closing issue
