### ISSUE TITLE
When use the key up and key down into grid the quantity panel is not update 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#92]

**Comment by marcalwestf** [comment]
With the commit, it happens the following:
- imagine you have an order with 5 lines
- you select the line #3
- you type in ALT+DOWN (once or twice), then the selection jumps to the first line
- once in the first line, ALT+DOWN does not affect the selection: it remains on line #1

**Comment by marcalwestf** [comment]
error persists in spite of changes ;(

**Comment by marcalwestf** [comment]
error is solved.
Closing issue
