### ISSUE TITLE
Screen Resolution Problem.

### ISSUE THREAD

**Issue by Andresdguez** [adempiere/adempierePOS#93]
In Monitor with resolution of 1024 x 768, the image is enlarged in the POS, the resolution looks bad.

**Comment by marcalwestf** [comment]
When solving this case, it should be also implemented for tablets, which are very common to take orders in places like restaurants.

**Comment by marcalwestf** [comment]
This is related to https://github.com/adempiere/adempierePOS/issues/115
As issue 115 is closed, this also.
